/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * gui.java
 *
 * Created on 6 déc. 2010, 19:31:50
 */

package planetediteur.gui;


import Events.appFocusListener;
import Events.appKeyListener;
import gui.test;
import java.io.File;
import java.io.IOException;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JTextArea;
import planetediteur.AutoString;
import planetediteur.Edit;


/**
 *
 * @author ohanessian
 */
public class gui extends  test{

    /** Creates new form gui */
    public gui(){

            initComponents();
     
            Edit tab = new Edit();
            tabEdit.add(tab);
            tab.setTab(jTab.getTabCount());
            jTab.addTab("new file",tabEdit.elementAt(0).getjScroll());
            jSearch.setVisible(false);
            JTextArea texte = tabEdit.elementAt(0).getjTexte();
            texte.addFocusListener(new appFocusListener("jTexte"));
            texte.addKeyListener(new appKeyListener("jTexte" , jList ,texte));

       }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFrame1 = new javax.swing.JFrame();
        jButton5 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jFrame2 = new javax.swing.JFrame();
        jChoix = new javax.swing.JFileChooser();
        jPopupMenu1 = new javax.swing.JPopupMenu();
        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu3 = new javax.swing.JMenu();
        jMenu4 = new javax.swing.JMenu();
        jPanel1 = new javax.swing.JPanel();
        jSave = new javax.swing.JButton();
        jNouveauTab = new javax.swing.JButton();
        test = new javax.swing.JButton();
        jFermer = new javax.swing.JButton();
        jOuvrir = new javax.swing.JButton();
        jToSearch = new javax.swing.JToggleButton();
        jEtat = new javax.swing.JLabel();
        jTab = new javax.swing.JTabbedPane();
        jSearch = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList = new javax.swing.JTextArea();
        jButton1 = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jCheckBoxMenuItem1 = new javax.swing.JCheckBoxMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem4 = new javax.swing.JMenuItem();

        jFrame1.setTitle("about");
        jFrame1.setMinimumSize(new java.awt.Dimension(403, 120));
        jFrame1.setResizable(false);

        jButton5.setText("Fermer");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jLabel1.setText("About::planetEditeur v0.1 auteur Ohanessian gregoire");

        javax.swing.GroupLayout jFrame1Layout = new javax.swing.GroupLayout(jFrame1.getContentPane());
        jFrame1.getContentPane().setLayout(jFrame1Layout);
        jFrame1Layout.setHorizontalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jFrame1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jFrame1Layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jFrame1Layout.createSequentialGroup()
                        .addComponent(jButton5)
                        .addGap(26, 26, 26))))
        );
        jFrame1Layout.setVerticalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jFrame1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton5)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jFrame2.setMinimumSize(new java.awt.Dimension(475, 530));

        jChoix.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jChoixActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jFrame2Layout = new javax.swing.GroupLayout(jFrame2.getContentPane());
        jFrame2.getContentPane().setLayout(jFrame2Layout);
        jFrame2Layout.setHorizontalGroup(
            jFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jFrame2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jChoix, javax.swing.GroupLayout.DEFAULT_SIZE, 451, Short.MAX_VALUE)
                .addContainerGap())
        );
        jFrame2Layout.setVerticalGroup(
            jFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jFrame2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jChoix, javax.swing.GroupLayout.DEFAULT_SIZE, 485, Short.MAX_VALUE)
                .addContainerGap())
        );

        jMenu3.setText("File");
        jMenuBar2.add(jMenu3);

        jMenu4.setText("Edit");
        jMenuBar2.add(jMenu4);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("PlanetEditeur");

        jPanel1.setBorder(null);

        jSave.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui/save.png"))); // NOI18N
        jSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jSaveActionPerformed(evt);
            }
        });

        jNouveauTab.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui/newTab.png"))); // NOI18N
        jNouveauTab.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jNouveauTabActionPerformed(evt);
            }
        });

        test.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui/noTab.png"))); // NOI18N
        test.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                testActionPerformed(evt);
            }
        });

        jFermer.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui/exit.png"))); // NOI18N
        jFermer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFermerActionPerformed(evt);
            }
        });

        jOuvrir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui/open.png"))); // NOI18N
        jOuvrir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jOuvrirActionPerformed(evt);
            }
        });

        jToSearch.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui/search.png"))); // NOI18N
        jToSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToSearchActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jOuvrir)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSave)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jToSearch)
                .addGap(70, 70, 70)
                .addComponent(jNouveauTab)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(test)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 291, Short.MAX_VALUE)
                .addComponent(jFermer)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jFermer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jOuvrir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jNouveauTab, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(test, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jSave, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jToSearch))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jEtat.setOpaque(true);

        jTab.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jTabMousePressed(evt);
            }
        });

        jSearch.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jSearchKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jSearchKeyReleased(evt);
            }
        });

        jList.setColumns(20);
        jList.setEditable(false);
        jList.setRows(5);
        jScrollPane1.setViewportView(jList);

        jButton1.setText("update");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jMenu1.setText("File");

        jMenuItem1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_O, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui/open.png"))); // NOI18N
        jMenuItem1.setText("ouvrir");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuItem2.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui/save.png"))); // NOI18N
        jMenuItem2.setText("sauvegarder");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);

        jCheckBoxMenuItem1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.CTRL_MASK));
        jCheckBoxMenuItem1.setSelected(true);
        jCheckBoxMenuItem1.setText("save-auto");
        jCheckBoxMenuItem1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui/run.png"))); // NOI18N
        jMenu1.add(jCheckBoxMenuItem1);

        jMenuItem3.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_Q, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui/exit.png"))); // NOI18N
        jMenuItem3.setText("quitter");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem3);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("aide");

        jMenuItem4.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F1, 0));
        jMenuItem4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui/about.png"))); // NOI18N
        jMenuItem4.setText("about");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem4);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton1))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jEtat, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(65, 65, 65)
                        .addComponent(jSearch, javax.swing.GroupLayout.DEFAULT_SIZE, 480, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTab, javax.swing.GroupLayout.DEFAULT_SIZE, 515, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTab, javax.swing.GroupLayout.DEFAULT_SIZE, 392, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 392, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jEtat, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        jFrame1.setVisible(true);
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        jFrame1.setVisible(false);
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jFermerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFermerActionPerformed
        this.quitter();
    }//GEN-LAST:event_jFermerActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        this.quitter();
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jNouveauTabActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jNouveauTabActionPerformed
      Edit tab = new Edit();
      tabEdit.add(tab);
      tab.setTab(jTab.getTabCount());
      jTab.addTab("new file",tabEdit.elementAt(jTab.getTabCount()).getjScroll());
      
        

      JTextArea texte = tabEdit.elementAt(jTab.getTabCount() - 1).getjTexte();
      texte.addFocusListener(new appFocusListener("jTexte"));
      texte.addKeyListener(new appKeyListener("jTexte" , jList ,texte));
                
        
    }//GEN-LAST:event_jNouveauTabActionPerformed

    private void jOuvrirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jOuvrirActionPerformed
                jFrame2.setVisible(true);
                choix = 'O';
                jEtat.setText("Ouverture");
    }//GEN-LAST:event_jOuvrirActionPerformed

    private void jChoixActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jChoixActionPerformed
            System.out.print(evt.getActionCommand());
           
            if(evt.getActionCommand().equals("CancelSelection"))
            {
                jFrame2.setVisible(false);
            }    
            else
            {
                if(choix == 'O')
                {    
                    jFrame2.setVisible(false);
                    File file = jChoix.getSelectedFile();
                    Edit tab = new Edit();
                    jEtat.setText("Ouverture en cours");
                    tabEdit.add(tab);
                    tab.setTab(jTab.getTabCount());
                    tab.setFichier(file);
                    jTab.addTab(file.getName(),tabEdit.elementAt(jTab.getTabCount()).getjScroll());
                    jTab.setSelectedIndex(jTab.getTabCount() - 1);
                   JTextArea texte = tabEdit.elementAt(jTab.getSelectedIndex()).getjTexte();
                    texte.addFocusListener(new appFocusListener("jTexte"));
                    texte.addKeyListener(new appKeyListener("jTexte" , jList ,texte));
                    jEtat.setText("Fichier ouvert");
                    
                }
                else if (choix == 'S')
                {
                    String name;
                    String rep;
                    jFrame2.setVisible(false);

                    //ON REGARDE LE FICHIER CHOISI POUR L'ENREGISTREMENT
                    File file = jChoix.getSelectedFile(); 
                    //ON RECUPERE LE TAB SELECTIONNER POUR AVOIR L'EDIT ACTUEL
                    Edit sauve = tabEdit.elementAt(jTab.getSelectedIndex());
                    
                    //ON PREPARE LE INFO POUR L'ENREGISTREMENT
                    name = file.getName();
                    rep = file.getPath();
                    sauve.setNom(name);
                    sauve.setRep(rep);
                  
                    System.out.print("\n" + rep );
                    try{
                        //ON SAUVEGARDE
                        jEtat.setText("sauvegarde en cour");
                        sauve.sauvegarde();
                        //ON CHANGE LE FICHIER DE L'EDIT
                        sauve.setFichier(new File(rep));
                        jTab.setTitleAt(jTab.getSelectedIndex(),sauve.getNom());
                        jEtat.setText("Sauvegarde effectuer");
                         
                    } 
                    catch (IOException ex) {
                    Logger.getLogger(gui.class.getName()).log(Level.SEVERE, null, ex);
                    }
                }
            }
            
           
    }//GEN-LAST:event_jChoixActionPerformed

    private void jSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jSaveActionPerformed
          jFrame2.setVisible(true);   
          choix = 'S';
          jEtat.setText("Sauvegarde");
                 
    }//GEN-LAST:event_jSaveActionPerformed
    
    ///Evenemement
    private void jTabActionPerformed(java.awt.event.ActionEvent evt) {
        
        System.out.print(tabEdit.elementAt(jTab.getSelectedIndex()).getjTexte().getText());
        
    }
    
    
    private void testActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_testActionPerformed
      if(jTab.getTabCount() > 1)
      {   
        jTab.remove(jTab.getSelectedIndex());
        tabEdit.remove(jTab.getSelectedIndex());
        System.out.print(jTab.getSelectedIndex());
      }
    }//GEN-LAST:event_testActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
          jFrame2.setVisible(true);   
          choix = 'S';
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
          jFrame2.setVisible(true);   
          choix = 'O';
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jToSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToSearchActionPerformed
        
        if(searchB)
        {    
            jSearch.setVisible(false);
            this.searchB = false;
        }
        else
        {
            this.searchB = true;
            jSearch.setVisible(true); 
        }
    }//GEN-LAST:event_jToSearchActionPerformed

    private void jSearchKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jSearchKeyPressed
       /* CompleteX test1 = new CompleteX();
        test1.setTexte(tabEdit.elementAt(jTab.getSelectedIndex()).getjTexte().getText());
        test1.setRecherche(jSearch.getText());
        System.out.print(test1.search());*/
    }//GEN-LAST:event_jSearchKeyPressed

    private void jTabMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTabMousePressed
       System.out.print(jTab.getSelectedIndex());
       System.out.print(tabEdit.elementAt(jTab.getSelectedIndex()).getjTexte().getText());
       
    }//GEN-LAST:event_jTabMousePressed

    private void jSearchKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jSearchKeyReleased
        
       /* test1.setTexte(tabEdit.elementAt(jTab.getSelectedIndex()).getjTexte().getText());
        test1.setRecherche(jSearch.getText());
        System.out.print(test1.search());*/
    }//GEN-LAST:event_jSearchKeyReleased

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        AutoString test = new AutoString();
        test.update(tabEdit.elementAt(jTab.getSelectedIndex()).getjTexte().getText());
        
        
        
    }//GEN-LAST:event_jButton1ActionPerformed
    
    private void quitter()
    {
        System.exit(0);
    }
    
    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
  
                    new gui().setVisible(true);
                
            
            }
        });
    }
    
    
    
    private Vector<Edit> tabEdit = new Vector();
    private Character choix = null;
    private boolean searchB = false;
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton5;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem1;
    private javax.swing.JFileChooser jChoix;
    private javax.swing.JLabel jEtat;
    private javax.swing.JButton jFermer;
    private javax.swing.JFrame jFrame1;
    private javax.swing.JFrame jFrame2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextArea jList;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JButton jNouveauTab;
    private javax.swing.JButton jOuvrir;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JButton jSave;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jSearch;
    private javax.swing.JTabbedPane jTab;
    private javax.swing.JToggleButton jToSearch;
    private javax.swing.JButton test;
    // End of variables declaration//GEN-END:variables



}

